/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './what-is-angular.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './what-is-angular.component.scss.shim';
import * as import10 from '../../shared/article-header/article-header.component';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '../../shared/next-nav/next-nav.component';
import * as import14 from '../../shared/article-header/article-header.component.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import17 from '../../shared/next-nav/next-nav.component.ngfactory';
import * as import18 from '../../shared/next-nav/next-nav.service';
import * as import19 from '../../shared/adsense/adsense.component';
import * as import20 from '../../shared/adsense/adsense.component.ngfactory';
export class Wrapper_WhatIsAngularComponent {
  /*private*/ _eventHandler:Function;
  context:import0.WhatIsAngularComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.WhatIsAngularComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_WhatIsAngularComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.WhatIsAngularComponent],import0.WhatIsAngularComponent,{})];
var renderType_WhatIsAngularComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_WhatIsAngularComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.WhatIsAngularComponent>;
  _WhatIsAngularComponent_0_3:Wrapper_WhatIsAngularComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WhatIsAngularComponent_Host0,renderType_WhatIsAngularComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_WhatIsAngularComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-what-is-angular',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_WhatIsAngularComponent0(this.viewUtils,this,0,this._el_0);
    this._WhatIsAngularComponent_0_3 = new Wrapper_WhatIsAngularComponent();
    this.compView_0.create(this._WhatIsAngularComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._WhatIsAngularComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WhatIsAngularComponent) && (0 === requestNodeIndex))) { return this._WhatIsAngularComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._WhatIsAngularComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const WhatIsAngularComponentNgFactory:import8.ComponentFactory<import0.WhatIsAngularComponent> = new import8.ComponentFactory<import0.WhatIsAngularComponent>('app-what-is-angular',View_WhatIsAngularComponent_Host0,import0.WhatIsAngularComponent);
const styles_WhatIsAngularComponent:any[] = [import9.styles];
const nodeDebugInfos_WhatIsAngularComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import10.ArticleHeaderComponent],import10.ArticleHeaderComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import11.TemplateRef,
    import12.NgIf
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import13.NextNavComponent],import13.NextNavComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_WhatIsAngularComponent:import3.RenderComponentType = import4.createRenderComponentType('C:/fuwari-angular/src/app/articles/what-is-angular/what-is-angular.component.html',0,import5.ViewEncapsulation.Emulated,styles_WhatIsAngularComponent,{});
export class View_WhatIsAngularComponent0 extends import1.DebugAppView<import0.WhatIsAngularComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  compView_6:import1.AppView<import10.ArticleHeaderComponent>;
  _ArticleHeaderComponent_6_3:import14.Wrapper_ArticleHeaderComponent;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import15.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import16.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  compView_96:import1.AppView<import13.NextNavComponent>;
  _NextNavComponent_96_3:import17.Wrapper_NextNavComponent;
  _text_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WhatIsAngularComponent0,renderType_WhatIsAngularComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_WhatIsAngularComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'section',new import4.InlineArray2(2,'class','section'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,25));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','container'),this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(3,1,25));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'article',new import4.InlineArray2(2,'class','article '),this.debug(4,3,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,3,30));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'article-header',import4.EMPTY_INLINE_ARRAY,this.debug(6,4,6));
    this.compView_6 = new import14.View_ArticleHeaderComponent0(this.viewUtils,this,6,this._el_6);
    this._ArticleHeaderComponent_6_3 = new import14.Wrapper_ArticleHeaderComponent();
    this.compView_6.create(this._ArticleHeaderComponent_6_3.context);
    this._text_7 = this.renderer.createText(this._el_4,'\n\n      ',this.debug(7,4,69));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_4,'div',new import4.InlineArray2(2,'class','content is-medium'),this.debug(8,6,6));
    this._text_9 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(9,6,37));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(10,8,8));
    this._text_11 = this.renderer.createText(this._el_10,'W3C Web Components をフレームワーク化したもの。',this.debug(11,8,11));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',this.debug(12,8,48));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(13,9,8));
    this._text_14 = this.renderer.createText(this._el_13,'SPA（Single-Page Application）を作ることができる。',this.debug(14,9,11));
    this._text_15 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(15,9,53));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(16,11,8));
    this._text_17 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(17,11,12));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_8,this.debug(18,13,8));
    this._vc_18 = new import15.ViewContainer(18,8,this,this._anchor_18);
    this._TemplateRef_18_5 = new import11.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import16.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(19,13,35));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(20,15,8));
    this._text_21 = this.renderer.createText(this._el_8,'\n        ',this.debug(21,15,12));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(22,16,8));
    this._text_23 = this.renderer.createText(this._el_22,'W3C Web Components って何？',this.debug(23,16,12));
    this._text_24 = this.renderer.createText(this._el_8,'\n        ',this.debug(24,16,40));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_8,'hr',import4.EMPTY_INLINE_ARRAY,this.debug(25,17,8));
    this._text_26 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(26,17,12));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(27,19,8));
    this._text_28 = this.renderer.createText(this._el_27,'Web を部品化するしくみ。',this.debug(28,19,11));
    this._text_29 = this.renderer.createText(this._el_8,'\n        ',this.debug(29,19,29));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_8,'ul',import4.EMPTY_INLINE_ARRAY,this.debug(30,20,8));
    this._text_31 = this.renderer.createText(this._el_30,'\n          ',this.debug(31,20,12));
    this._el_32 = import4.createRenderElement(this.renderer,this._el_30,'li',import4.EMPTY_INLINE_ARRAY,this.debug(32,21,10));
    this._text_33 = this.renderer.createText(this._el_32,'Custom Element … 独自タグを定義する',this.debug(33,21,14));
    this._text_34 = this.renderer.createText(this._el_30,'\n          ',this.debug(34,21,45));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_30,'li',import4.EMPTY_INLINE_ARRAY,this.debug(35,22,10));
    this._text_36 = this.renderer.createText(this._el_35,'HTML Template … HTMLを部品化する',this.debug(36,22,14));
    this._text_37 = this.renderer.createText(this._el_30,'\n          ',this.debug(37,22,45));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_30,'li',import4.EMPTY_INLINE_ARRAY,this.debug(38,23,10));
    this._text_39 = this.renderer.createText(this._el_38,'HTML Imports … 部品化したHTMLを取り込む',this.debug(39,23,14));
    this._text_40 = this.renderer.createText(this._el_30,'\n          ',this.debug(40,23,48));
    this._el_41 = import4.createRenderElement(this.renderer,this._el_30,'li',import4.EMPTY_INLINE_ARRAY,this.debug(41,24,10));
    this._text_42 = this.renderer.createText(this._el_41,'Shadow DOM（Scoped CSS） … DOMをカプセル化する',this.debug(42,24,14));
    this._text_43 = this.renderer.createText(this._el_30,'\n        ',this.debug(43,24,55));
    this._text_44 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(44,25,13));
    this._el_45 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(45,27,8));
    this._text_46 = this.renderer.createText(this._el_8,'\n        ',this.debug(46,27,12));
    this._el_47 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(47,28,8));
    this._text_48 = this.renderer.createText(this._el_47,'W3C Web Components のイメージ',this.debug(48,28,12));
    this._text_49 = this.renderer.createText(this._el_8,'\n        ',this.debug(49,28,41));
    this._el_50 = import4.createRenderElement(this.renderer,this._el_8,'hr',import4.EMPTY_INLINE_ARRAY,this.debug(50,29,8));
    this._text_51 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(51,29,12));
    this._el_52 = import4.createRenderElement(this.renderer,this._el_8,'img',new import4.InlineArray8(6,'height','402px','src','http://cdn.banana-juice.com/angular/img/what-is-angular/w3c_web_components.png','width','615px'),this.debug(52,31,8));
    this._text_53 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(53,31,127));
    this._el_54 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(54,33,8));
    this._text_55 = this.renderer.createText(this._el_8,'\n        ',this.debug(55,33,12));
    this._el_56 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(56,34,8));
    this._text_57 = this.renderer.createText(this._el_56,'SPA（Single-Page Application）って何？',this.debug(57,34,12));
    this._text_58 = this.renderer.createText(this._el_8,'\n        ',this.debug(58,34,49));
    this._el_59 = import4.createRenderElement(this.renderer,this._el_8,'hr',import4.EMPTY_INLINE_ARRAY,this.debug(59,35,8));
    this._text_60 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(60,35,12));
    this._el_61 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(61,37,8));
    this._text_62 = this.renderer.createText(this._el_61,'ひとつのページで完結したWebアプリケーション。',this.debug(62,37,11));
    this._text_63 = this.renderer.createText(this._el_8,'\n        ',this.debug(63,37,39));
    this._el_64 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(64,38,8));
    this._text_65 = this.renderer.createText(this._el_64,'ページ遷移はせず、DOM操作により切り替える。',this.debug(65,38,11));
    this._text_66 = this.renderer.createText(this._el_8,'\n        ',this.debug(66,38,38));
    this._el_67 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(67,39,8));
    this._text_68 = this.renderer.createText(this._el_67,'サーバとのやりとりは、REST や WebSocket などで行う。',this.debug(68,39,11));
    this._text_69 = this.renderer.createText(this._el_8,'\n        ',this.debug(69,39,49));
    this._el_70 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(70,40,8));
    this._text_71 = this.renderer.createText(this._el_8,'\n        ',this.debug(71,40,12));
    this._el_72 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(72,41,8));
    this._text_73 = this.renderer.createText(this._el_72,'対比されるのは、MPA (Multi-Page Application）。',this.debug(73,41,11));
    this._text_74 = this.renderer.createText(this._el_8,'\n        ',this.debug(74,41,52));
    this._el_75 = import4.createRenderElement(this.renderer,this._el_8,'p',import4.EMPTY_INLINE_ARRAY,this.debug(75,42,8));
    this._text_76 = this.renderer.createText(this._el_75,'MPA は従来のWebアプリケーション。',this.debug(76,42,11));
    this._text_77 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(77,42,35));
    this._el_78 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(78,44,8));
    this._text_79 = this.renderer.createText(this._el_8,'\n        ',this.debug(79,44,12));
    this._el_80 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(80,45,8));
    this._text_81 = this.renderer.createText(this._el_80,'SPA と MPA のイメージ比較',this.debug(81,45,12));
    this._text_82 = this.renderer.createText(this._el_8,'\n        ',this.debug(82,45,34));
    this._el_83 = import4.createRenderElement(this.renderer,this._el_8,'hr',import4.EMPTY_INLINE_ARRAY,this.debug(83,46,8));
    this._text_84 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(84,46,12));
    this._el_85 = import4.createRenderElement(this.renderer,this._el_8,'img',new import4.InlineArray8(6,'height','507px','src','http://cdn.banana-juice.com/angular/img/what-is-angular/spa_vs_mpa_by_image.png','width','792px'),this.debug(85,48,8));
    this._text_86 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(86,48,128));
    this._el_87 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,this.debug(87,50,8));
    this._text_88 = this.renderer.createText(this._el_8,'\n        ',this.debug(88,50,12));
    this._el_89 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,this.debug(89,51,8));
    this._text_90 = this.renderer.createText(this._el_89,'SPA と MPA のアーキテクチャ比較',this.debug(90,51,12));
    this._text_91 = this.renderer.createText(this._el_8,'\n        ',this.debug(91,51,37));
    this._el_92 = import4.createRenderElement(this.renderer,this._el_8,'hr',import4.EMPTY_INLINE_ARRAY,this.debug(92,52,8));
    this._text_93 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(93,52,12));
    this._el_94 = import4.createRenderElement(this.renderer,this._el_8,'img',new import4.InlineArray8(6,'height','445px','src','http://cdn.banana-juice.com/angular/img/what-is-angular/spa_vs_mpa_by_architecture.png','width','547px'),this.debug(94,54,8));
    this._text_95 = this.renderer.createText(this._el_8,'\n\n        ',this.debug(95,54,135));
    this._el_96 = import4.createRenderElement(this.renderer,this._el_8,'next-nav',import4.EMPTY_INLINE_ARRAY,this.debug(96,56,8));
    this.compView_96 = new import17.View_NextNavComponent0(this.viewUtils,this,96,this._el_96);
    this._NextNavComponent_96_3 = new import17.Wrapper_NextNavComponent(this.parentView.injectorGet(import18.NextNavService,this.parentIndex));
    this.compView_96.create(this._NextNavComponent_96_3.context);
    this._text_97 = this.renderer.createText(this._el_8,'\n      ',this.debug(97,56,29));
    this._text_98 = this.renderer.createText(this._el_4,'\n      ',this.debug(98,57,12));
    this._text_99 = this.renderer.createText(this._el_4,'\n    ',this.debug(99,58,24));
    this._text_100 = this.renderer.createText(this._el_2,'\n\n  ',this.debug(100,59,14));
    this._text_101 = this.renderer.createText(this._el_0,'\n  ',this.debug(101,61,8));
    this._text_102 = this.renderer.createText(this._el_0,'\n',this.debug(102,62,22));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._text_102
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.ArticleHeaderComponent) && (6 === requestNodeIndex))) { return this._ArticleHeaderComponent_6_3.context; }
    if (((token === import11.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import12.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import13.NextNavComponent) && (96 === requestNodeIndex))) { return this._NextNavComponent_96_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(6,4,22);
    const currVal_6_0_0:any = this.context.title;
    this._ArticleHeaderComponent_6_3.check_title(currVal_6_0_0,throwOnChange,false);
    this.debug(6,4,38);
    const currVal_6_0_1:any = this.context.date;
    this._ArticleHeaderComponent_6_3.check_date(currVal_6_0_1,throwOnChange,false);
    this._ArticleHeaderComponent_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this.debug(18,13,13);
    const currVal_18_0_0:any = this.context.display;
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    this.debug(96,56,8);
    this._NextNavComponent_96_3.ngDoCheck(this,this._el_96,throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this.compView_6.detectChanges(throwOnChange);
    this.compView_96.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_18.destroyNestedViews();
    this.compView_6.destroy();
    this.compView_96.destroy();
    this.debug(6,4,6);
    this.debug(18,13,8);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 18)) { return new View_WhatIsAngularComponent1(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    return (null as any);
  }
}
const nodeDebugInfos_WhatIsAngularComponent1:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import19.AdsenseComponent],import19.AdsenseComponent,{})];
class View_WhatIsAngularComponent1 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import19.AdsenseComponent>;
  _AdsenseComponent_0_3:import20.Wrapper_AdsenseComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_WhatIsAngularComponent1,renderType_WhatIsAngularComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_WhatIsAngularComponent1,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'ads',import4.EMPTY_INLINE_ARRAY,this.debug(0,13,8));
    this.compView_0 = new import20.View_AdsenseComponent0(this.viewUtils,this,0,this._el_0);
    this._AdsenseComponent_0_3 = new import20.Wrapper_AdsenseComponent();
    this.compView_0.create(this._AdsenseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.AdsenseComponent) && (0 === requestNodeIndex))) { return this._AdsenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,13,8);
    this._AdsenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}