/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './adsense.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from './adsense.component.scss.shim';
import * as import10 from 'ng2-adsense/ng2-adsense';
import * as import11 from '../../../../node_modules/ng2-adsense/ng2-adsense.ngfactory';
export class Wrapper_AdsenseComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AdsenseComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AdsenseComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const nodeDebugInfos_AdsenseComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.AdsenseComponent],import0.AdsenseComponent,{})];
var renderType_AdsenseComponent_Host:import3.RenderComponentType = import4.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_AdsenseComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AdsenseComponent>;
  _AdsenseComponent_0_3:Wrapper_AdsenseComponent;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdsenseComponent_Host0,renderType_AdsenseComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AdsenseComponent_Host0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ads',import4.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_AdsenseComponent0(this.viewUtils,this,0,this._el_0);
    this._AdsenseComponent_0_3 = new Wrapper_AdsenseComponent();
    this.compView_0.create(this._AdsenseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._AdsenseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AdsenseComponent) && (0 === requestNodeIndex))) { return this._AdsenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._AdsenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AdsenseComponentNgFactory:import8.ComponentFactory<import0.AdsenseComponent> = new import8.ComponentFactory<import0.AdsenseComponent>('ads',View_AdsenseComponent_Host0,import0.AdsenseComponent);
const styles_AdsenseComponent:any[] = [import9.styles];
const nodeDebugInfos_AdsenseComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([import10.AdsenseComponent],import10.AdsenseComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_AdsenseComponent:import3.RenderComponentType = import4.createRenderComponentType('C:/fuwari-angular/src/app/shared/adsense/adsense.component.html',0,import5.ViewEncapsulation.Emulated,styles_AdsenseComponent,{});
export class View_AdsenseComponent0 extends import1.DebugAppView<import0.AdsenseComponent> {
  _el_0:any;
  compView_0:import1.AppView<import10.AdsenseComponent>;
  _AdsenseComponent_0_3:import11.Wrapper_AdsenseComponent;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AdsenseComponent0,renderType_AdsenseComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_AdsenseComponent0);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'ng2-adsense',import4.EMPTY_INLINE_ARRAY,this.debug(0,0,0));
    this.compView_0 = new import11.View_AdsenseComponent0(this.viewUtils,this,0,this._el_0);
    this._AdsenseComponent_0_3 = new import11.Wrapper_AdsenseComponent();
    this._text_1 = this.renderer.createText((null as any),'\n',this.debug(1,2,24));
    this.compView_0.create(this._AdsenseComponent_0_3.context);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.AdsenseComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._AdsenseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,1,2);
    const currVal_0_0_0:any = 'ca-pub-4398400415874126';
    this._AdsenseComponent_0_3.check_adClient(currVal_0_0_0,throwOnChange,false);
    this.debug(0,2,2);
    const currVal_0_0_1:any = 7651079037;
    this._AdsenseComponent_0_3.check_adSlot(currVal_0_0_1,throwOnChange,false);
    this._AdsenseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(0,0,0);
      if ((this.numberOfChecks === 0)) { this._AdsenseComponent_0_3.context.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
}