/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.section[_ngcontent-%COMP%] {\n  background-color: #F5F5F5;\n}\n.date[_ngcontent-%COMP%] {\n  font-size: 11px;\n\n  &:before {\n    content: "-";\n    margin-right: 5px;\n  }\n  &:after {\n    content: "-";\n    margin-left: 5px;\n  }\n}'];