/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.thumbnails[_ngcontent-%COMP%] {\n  list-style-type: none;\n  margin-left: 0;\n}\n.thumbnail-list[_ngcontent-%COMP%] {\n  margin: 0 5px 1px 0;\n  float: left;\n  height: 100px;\n  overflow: hidden;\n}\n.thumbnail-image[_ngcontent-%COMP%] {\n  width: 100px;\n\n  &:hover {\n    cursor: pointer;\n  }\n}\n.clear[_ngcontent-%COMP%] {\n  clear: both;\n}'];